// <auto-generated />
using System;
using HomeWorke.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeWorke.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727023108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double?>("HoursWorked")
                        .HasColumnType("float");

                    b.Property<bool>("IsManuallyAdjusted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TimeApiFailed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClockIn");

                    b.HasIndex("EmployeeId", "ShiftDate");

                    b.ToTable("AttendanceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClockIn = new DateTime(2026, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 1, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(974),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 2,
                            ClockIn = new DateTime(2026, 1, 12, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 1, 12, 17, 5, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1533),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Late",
                            ShiftDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 3,
                            ClockIn = new DateTime(2026, 2, 3, 7, 55, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 2, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1548),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 4,
                            ClockIn = new DateTime(2026, 3, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1550),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 5,
                            ClockIn = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 4, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1552),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 6,
                            ClockIn = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 5, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1578),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Late",
                            ShiftDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 7,
                            ClockIn = new DateTime(2026, 6, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1580),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 8,
                            ClockIn = new DateTime(2026, 6, 28, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1582),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 9,
                            ClockIn = new DateTime(2026, 7, 4, 7, 50, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 4, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1584),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — Present",
                            ShiftDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 10,
                            ClockIn = new DateTime(2026, 7, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1586),
                            EmployeeId = 1,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Admin — EarlyDeparture",
                            ShiftDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 11,
                            ClockIn = new DateTime(2026, 1, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 1, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1589),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 12,
                            ClockIn = new DateTime(2026, 2, 15, 8, 5, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 2, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1592),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 13,
                            ClockIn = new DateTime(2026, 3, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 3, 8, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1593),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 14,
                            ClockIn = new DateTime(2026, 4, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1595),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 15,
                            ClockIn = new DateTime(2026, 5, 5, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 5, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1597),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Late",
                            ShiftDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 16,
                            ClockIn = new DateTime(2026, 5, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 5, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1598),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 17,
                            ClockIn = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 6, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1600),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 18,
                            ClockIn = new DateTime(2026, 7, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 1, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1604),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 19,
                            ClockIn = new DateTime(2026, 7, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1606),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 20,
                            ClockIn = new DateTime(2026, 7, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1607),
                            EmployeeId = 2,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Manager — Present",
                            ShiftDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 21,
                            ClockIn = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 1, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1614),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 22,
                            ClockIn = new DateTime(2026, 2, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 2, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1617),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 23,
                            ClockIn = new DateTime(2026, 3, 5, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1619),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Late",
                            ShiftDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 24,
                            ClockIn = new DateTime(2026, 4, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 4, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1620),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 25,
                            ClockIn = new DateTime(2026, 4, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1625),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 26,
                            ClockIn = new DateTime(2026, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 5, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1627),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 27,
                            ClockIn = new DateTime(2026, 6, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 6, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1629),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 28,
                            ClockIn = new DateTime(2026, 6, 18, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 6, 18, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1630),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Late",
                            ShiftDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 29,
                            ClockIn = new DateTime(2026, 7, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1642),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 30,
                            ClockIn = new DateTime(2026, 7, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 8, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1648),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 31,
                            ClockIn = new DateTime(2026, 7, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1701),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — Present",
                            ShiftDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TimeApiFailed = false
                        },
                        new
                        {
                            Id = 32,
                            ClockIn = new DateTime(2026, 7, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ClockOut = new DateTime(2026, 7, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2026, 7, 27, 2, 31, 5, 545, DateTimeKind.Utc).AddTicks(1703),
                            EmployeeId = 3,
                            IsManuallyAdjusted = false,
                            Notes = "Seed record for Employee — EarlyDeparture",
                            ShiftDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TimeApiFailed = false
                        });
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":0,\"note\":\"Demo audit entry #1\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":1,\"note\":\"Demo audit entry #2\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 4, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":2,\"note\":\"Demo audit entry #3\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 7, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":3,\"note\":\"Demo audit entry #4\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 10, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":4,\"note\":\"Demo audit entry #5\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 13, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Action = "AdminCreateDepartment",
                            EntityId = 1,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":5,\"note\":\"Demo audit entry #6\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 16, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Action = "DeleteDepartment",
                            EntityId = 2,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":6,\"note\":\"Demo audit entry #7\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 19, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Action = "AdminCreateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":7,\"note\":\"Demo audit entry #8\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 22, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Action = "ActivateEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":8,\"note\":\"Demo audit entry #9\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 25, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":9,\"note\":\"Demo audit entry #10\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 28, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":10,\"note\":\"Demo audit entry #11\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 1, 31, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":11,\"note\":\"Demo audit entry #12\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 3, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":12,\"note\":\"Demo audit entry #13\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 6, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":13,\"note\":\"Demo audit entry #14\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 9, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":14,\"note\":\"Demo audit entry #15\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 12, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Action = "AdminCreateDepartment",
                            EntityId = 1,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":15,\"note\":\"Demo audit entry #16\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 15, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Action = "DeleteDepartment",
                            EntityId = 2,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":16,\"note\":\"Demo audit entry #17\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 18, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Action = "AdminCreateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":17,\"note\":\"Demo audit entry #18\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 21, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Action = "ActivateEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":18,\"note\":\"Demo audit entry #19\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 24, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":19,\"note\":\"Demo audit entry #20\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 2, 27, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":20,\"note\":\"Demo audit entry #21\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":21,\"note\":\"Demo audit entry #22\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 5, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":22,\"note\":\"Demo audit entry #23\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 8, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":23,\"note\":\"Demo audit entry #24\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 11, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":24,\"note\":\"Demo audit entry #25\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Action = "AdminCreateDepartment",
                            EntityId = 1,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":25,\"note\":\"Demo audit entry #26\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 18, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteDepartment",
                            EntityId = 2,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":26,\"note\":\"Demo audit entry #27\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 21, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Action = "AdminCreateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":27,\"note\":\"Demo audit entry #28\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 24, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Action = "ActivateEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":28,\"note\":\"Demo audit entry #29\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 27, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":29,\"note\":\"Demo audit entry #30\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 3, 30, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":30,\"note\":\"Demo audit entry #31\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 2, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":31,\"note\":\"Demo audit entry #32\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 5, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":32,\"note\":\"Demo audit entry #33\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 8, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":33,\"note\":\"Demo audit entry #34\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":34,\"note\":\"Demo audit entry #35\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 14, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            Action = "AdminCreateDepartment",
                            EntityId = 1,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":35,\"note\":\"Demo audit entry #36\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 17, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            Action = "DeleteDepartment",
                            EntityId = 2,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":36,\"note\":\"Demo audit entry #37\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 20, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            Action = "AdminCreateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":37,\"note\":\"Demo audit entry #38\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 23, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            Action = "ActivateEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":38,\"note\":\"Demo audit entry #39\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 26, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":39,\"note\":\"Demo audit entry #40\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 4, 29, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":40,\"note\":\"Demo audit entry #41\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 2, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":41,\"note\":\"Demo audit entry #42\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":42,\"note\":\"Demo audit entry #43\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 8, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":43,\"note\":\"Demo audit entry #44\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 11, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":44,\"note\":\"Demo audit entry #45\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 14, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            Action = "AdminCreateDepartment",
                            EntityId = 1,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":45,\"note\":\"Demo audit entry #46\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 17, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            Action = "DeleteDepartment",
                            EntityId = 2,
                            EntityName = "Department",
                            NewValue = "{\"seed\":true,\"index\":46,\"note\":\"Demo audit entry #47\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 20, 22, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            Action = "AdminCreateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":47,\"note\":\"Demo audit entry #48\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 23, 23, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            Action = "ActivateEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":48,\"note\":\"Demo audit entry #49\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":49,\"note\":\"Demo audit entry #50\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 5, 30, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            Action = "AdminCreateEmployee",
                            EntityId = 1,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":50,\"note\":\"Demo audit entry #51\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 6, 2, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            Action = "ActivateEmployee",
                            EntityId = 2,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":51,\"note\":\"Demo audit entry #52\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 6, 5, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            Action = "DeactivateEmployee",
                            EntityId = 3,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":52,\"note\":\"Demo audit entry #53\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 6, 8, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            Action = "DeleteEmployee",
                            EntityId = 4,
                            EntityName = "Employee",
                            NewValue = "{\"seed\":true,\"index\":53,\"note\":\"Demo audit entry #54\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 6, 11, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            Action = "AdminAdjustment",
                            EntityId = 5,
                            EntityName = "AttendanceRecord",
                            NewValue = "{\"seed\":true,\"index\":54,\"note\":\"Demo audit entry #55\"}",
                            PerformedByEmployeeId = 1,
                            Timestamp = new DateTime(2026, 6, 14, 6, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software Development & IT",
                            IsActive = true,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "HR & People Operations",
                            IsActive = true,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Marketing & Communications",
                            IsActive = true,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finance & Accounting",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Business Operations",
                            IsActive = true,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "admin@homeworke.com",
                            EmployeeCode = "EMP-ADMIN",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$2gng1TarkDXhYAc3gOnI6ep6rDL/FRrEuh2Yp67PLnMDfRQ66od/C",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "manager@homeworke.com",
                            EmployeeCode = "EMP-MGR",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Manager",
                            PasswordHash = "$2a$11$Kdsnvh4rfAN/sUPcjQJzEuMtPXByVUi1vBdZ265yPU1MF2QxDb8Ee",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "demo@homeworke.com",
                            EmployeeCode = "EMP-DEMO",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "User",
                            ManagerId = 2,
                            PasswordHash = "$2a$11$kDpu6axhISWhoL8JJdq1p.ymYaGBq71.dAl4AsOF9yESrrPvI57s2",
                            Role = 0
                        });
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("HomeWorke.Api.Models.Domain.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.Employee", b =>
                {
                    b.HasOne("HomeWorke.Api.Models.Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HomeWorke.Api.Models.Domain.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HomeWorke.Api.Models.Domain.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
